export const treasuryAuditActions = {
  transactionManualCreate: "treasury.transaction.manual_create",
  transactionWatcherCreate: "treasury.transaction.watcher_create",
  transactionClassify: "treasury.transaction.classify",
  transactionStatusTransition: "treasury.transaction.status_transition",
  transactionVerify: "treasury.transaction.verify",
  transactionReject: "treasury.transaction.reject",
  transactionDuplicate: "treasury.transaction.duplicate",
  transactionReconciliationReopen: "treasury.transaction.reconciliation_reopen",
  transactionCorrectionLink: "treasury.transaction.correction_link",
  transactionDetailPublication: "treasury.transaction.detail_publication",
  commitmentCreate: "treasury.commitment.create",
  commitmentApprove: "treasury.commitment.approve",
  commitmentRelease: "treasury.commitment.release",
  commitmentFulfill: "treasury.commitment.fulfill",
  commitmentCancel: "treasury.commitment.cancel",
  inceptionCreate: "treasury.inception.create",
  inceptionActivate: "treasury.inception.activate",
  inceptionSupersede: "treasury.inception.supersede",
  watchedAddressCreate: "treasury.watched_address.create",
  watchedAddressUpdate: "treasury.watched_address.update",
  budgetCreate: "treasury.budget.create",
  budgetUpdate: "treasury.budget.update",
  fundingNeedCreate: "treasury.funding_need.create",
  fundingNeedUpdate: "treasury.funding_need.update",
  idealBudgetCreate: "treasury.ideal_budget.create",
  idealBudgetPublish: "treasury.ideal_budget.publish",
  runwayPlanCreate: "treasury.runway_plan.create",
  runwayPlanActivate: "treasury.runway_plan.activate",
  runwaySnapshotRefresh: "treasury.runway.snapshot_refresh",
  settingsUpdate: "treasury.settings.update",
  attributionCreate: "treasury.attribution.create",
  evidenceLink: "treasury.evidence.link",
  evidenceUnlink: "treasury.evidence.unlink",
  evidenceVisibility: "treasury.evidence.visibility",
  evidenceUpload: "treasury.evidence.upload",
  counterpartyCreate: "treasury.counterparty.create",
  counterpartyUpdate: "treasury.counterparty.update",
  accountCreate: "treasury.account.create",
  accountUpdate: "treasury.account.update",
  categoryCreate: "treasury.category.create",
  categoryUpdate: "treasury.category.update",
  projectCreate: "treasury.project.create",
  projectUpdate: "treasury.project.update",
} as const;

export type TreasuryAuditAction = (typeof treasuryAuditActions)[keyof typeof treasuryAuditActions];

export const treasuryEntityTypes = {
  transaction: "treasury_transaction",
  commitment: "treasury_commitment",
  inception: "treasury_ledger_inception",
  revision: "treasury_transaction_revision",
  commitmentRevision: "treasury_commitment_revision",
  watchedAddress: "treasury_watched_address",
  budget: "treasury_budget",
  fundingNeed: "treasury_funding_need",
  idealBudget: "treasury_ideal_annual_budget",
  runwayPlan: "treasury_runway_plan",
  runwaySnapshot: "treasury_runway_snapshot",
  settings: "treasury_publication_settings",
  attribution: "treasury_contribution_attribution",
  evidence: "treasury_evidence_object",
  counterparty: "treasury_counterparty",
  account: "treasury_account",
  category: "treasury_category",
  project: "treasury_project",
} as const;
