export type {
  RiskCheckName,
  RiskDecision,
  RiskDecisionOutcome,
  RiskResizeHint,
  RiskSnapshot,
} from "@/lib/trader/risk/types";
export {
  riskReasonCodes,
  capitalReasonCodes,
  engineReasonCodes,
  killSwitchReasonCodes,
  tradeAbuseReasonCodes,
  type CapitalLimitsReasonCode,
  type EngineReasonCode,
  type KillSwitchReasonCode,
  type RiskReasonCode,
  type TradeAbuseReasonCode,
} from "@/lib/trader/risk/reason-codes";
export {
  approveDecision,
  buildRiskSnapshot,
  closeOnlyDecision,
  isTerminalReject,
  mergeReasonCodes,
  rejectDecision,
  resizeDecision,
  stopAccountDecision,
  type BuildRiskSnapshotInput,
} from "@/lib/trader/risk/decision";
export {
  DECIMAL_SCALE,
  DECIMAL_SCALE_FACTOR,
  InvalidDecimalError,
  absDecimal,
  addDecimal,
  compareDecimal,
  divideDecimal,
  floorDecimal,
  formatDecimal,
  isPositiveDecimal,
  isZeroDecimal,
  minDecimal,
  multiplyDecimal,
  parseDecimal,
  subtractDecimal,
  type ScaledDecimal,
} from "@/lib/trader/risk/numeric";
export {
  createInMemoryOrderRateStore,
  InMemoryOrderRateStore,
} from "@/lib/trader/risk/order-rate-store";
export type {
  AccountRiskState,
  CapitalLimitsConfig,
  CapitalLimitsEvaluationInput,
  CapitalLimitsEvaluationResult,
  CapitalLimitsEvaluatorDeps,
  PositionSnapshot,
} from "@/lib/trader/risk/capital-limits.types";
export { evaluateCapitalLimits } from "@/lib/trader/risk/capital-limits-evaluator";
export type {
  OrderRateStore,
  TradeAbuseEvaluationInput,
  TradeAbuseEvaluationResult,
  TradeAbuseEvaluatorDeps,
  TradeAbuseLimitsConfig,
} from "@/lib/trader/risk/trade-abuse.types";
export { evaluateTradeAbuse } from "@/lib/trader/risk/trade-abuse-evaluator";
export {
  createPostgresRiskEngineService,
  createRiskEngineService,
  createSqliteRiskEngineService,
} from "@/lib/trader/risk/risk-engine-service";
export type {
  EvaluateOrderRequestInput,
  KillSwitchResolverPort,
  RiskEngineDecision,
  RiskEngineService,
  RiskEngineServiceDeps,
} from "@/lib/trader/risk/evaluate.types";
export {
  buildKillSwitchAuditMetadata,
  mapEffectiveStateToDecision,
  type KillSwitchEnforcementResult,
} from "@/lib/trader/risk/kill-switch-enforcement";
export {
  createPostgresRiskLimitsService,
  createRiskLimitsService,
  createSqliteRiskLimitsService,
  DEFAULT_ORG_RISK_LIMITS,
  diffRiskLimitsConfig,
  normalizeAndValidateRiskLimitsInput,
  RiskLimitsValidationError,
  riskLimitsConfigEquals,
  toCapitalLimitsConfig,
  toOrgRiskLimitsMetadata,
  toTradeAbuseLimitsConfig,
  type NormalizedRiskLimitsConfig,
  type OrgRiskLimitsMetadata,
  type RiskLimitsRepository,
  type RiskLimitsService,
  type UpsertOrgRiskLimitsInput,
} from "@/lib/trader/risk/limits";
export {
  createKillSwitchResolver,
  createKillSwitchService,
  createPostgresKillSwitchRepository,
  createPostgresKillSwitchService,
  createSqliteKillSwitchRepository,
  createSqliteKillSwitchService,
  assertAllowedTransition,
  failClosedEffectiveState,
  isEnforcingState,
  mergeEffectiveContributions,
  mostRestrictiveEnforcementMode,
  KillSwitchAuthorizationError,
  KillSwitchConcurrencyError,
  KillSwitchNotFoundError,
  IllegalKillSwitchTransitionError,
  UnsupportedKillSwitchScopeError,
  toKillSwitchView,
  type EffectiveKillSwitchState,
  type EffectiveContribution,
  type KillSwitchActor,
  type KillSwitchRepository,
  type KillSwitchRow,
  type KillSwitchScopeKey,
  type KillSwitchService,
  type KillSwitchServiceDeps,
  type KillSwitchTarget,
  type KillSwitchTransitionResult,
  type KillSwitchView,
  type TripKillSwitchInput,
} from "@/lib/trader/risk/kill-switch";
