export type {
  RiskCheckName,
  RiskDecision,
  RiskDecisionOutcome,
  RiskResizeHint,
  RiskSnapshot,
} from "@/lib/trader/risk/types";
export {
  riskReasonCodes,
  capitalReasonCodes,
  engineReasonCodes,
  killSwitchReasonCodes,
  tradeAbuseReasonCodes,
  type CapitalLimitsReasonCode,
  type EngineReasonCode,
  type KillSwitchReasonCode,
  type RiskReasonCode,
  type TradeAbuseReasonCode,
} from "@/lib/trader/risk/reason-codes";
export {
  approveDecision,
  buildRiskSnapshot,
  closeOnlyDecision,
  isTerminalReject,
  mergeReasonCodes,
  rejectDecision,
  resizeDecision,
  stopAccountDecision,
  type BuildRiskSnapshotInput,
} from "@/lib/trader/risk/decision";
export {
  DECIMAL_SCALE,
  DECIMAL_SCALE_FACTOR,
  InvalidDecimalError,
  absDecimal,
  addDecimal,
  compareDecimal,
  divideDecimal,
  floorDecimal,
  formatDecimal,
  isPositiveDecimal,
  isZeroDecimal,
  minDecimal,
  multiplyDecimal,
  parseDecimal,
  subtractDecimal,
  type ScaledDecimal,
} from "@/lib/trader/risk/numeric";
export {
  createInMemoryOrderRateStore,
  InMemoryOrderRateStore,
} from "@/lib/trader/risk/order-rate-store";
export type {
  AccountRiskState,
  CapitalLimitsConfig,
  CapitalLimitsEvaluationInput,
  CapitalLimitsEvaluationResult,
  CapitalLimitsEvaluatorDeps,
  PositionSnapshot,
} from "@/lib/trader/risk/capital-limits.types";
export { evaluateCapitalLimits } from "@/lib/trader/risk/capital-limits-evaluator";
export type {
  OrderRateStore,
  TradeAbuseEvaluationInput,
  TradeAbuseEvaluationResult,
  TradeAbuseEvaluatorDeps,
  TradeAbuseLimitsConfig,
} from "@/lib/trader/risk/trade-abuse.types";
export { evaluateTradeAbuse } from "@/lib/trader/risk/trade-abuse-evaluator";
export {
  createPostgresRiskEngineService,
  createRiskEngineService,
  createSqliteRiskEngineService,
} from "@/lib/trader/risk/risk-engine-service";
export {
  emitKillSwitchDataQualityCounter,
  emitRiskReasonCodeCounter,
  KILL_SWITCH_DATA_QUALITY_COUNTER_CODE,
  RISK_COUNTER_CODES,
  type EmitKillSwitchDataQualityCounterInput,
  type EmitRiskReasonCodeCounterInput,
} from "@/lib/trader/risk/risk-telemetry";
export type {
  EvaluateOrderRequestInput,
  KillSwitchResolverPort,
  RiskEngineDecision,
  RiskEngineService,
  RiskEngineServiceDeps,
} from "@/lib/trader/risk/evaluate.types";
export {
  buildKillSwitchAuditMetadata,
  mapEffectiveStateToDecision,
  mapKillFoldToDecision,
  type KillSwitchEnforcementResult,
} from "@/lib/trader/risk/kill-switch-enforcement";
export {
  assertAuthorityChainStageOrdering,
  assertExecutionWithinRiskAuthority,
  assertHypothesisConfidenceNonAuthoritative,
  AUTHORITY_CHAIN_STAGES,
  AuthorityChainViolationError,
  CAPITAL_AUTHORITY_CHAIN_VERSION,
  clampRiskProposalDownwardOnly,
  extractLegacyStrategyDiagnostics,
  isV2CapitalAuthorityPath,
  RiskImprovementForbiddenError,
  V2_CAPITAL_AUTHORITY_PATH,
  type AuthorityChainStage,
  type CapitalAuthorityPath,
  type LegacyStrategyDiagnostics,
} from "@/lib/trader/risk/authority-chain";
export {
  createPostgresRiskLimitsService,
  createRiskLimitsService,
  createSqliteRiskLimitsService,
  DEFAULT_ORG_RISK_LIMITS,
  diffRiskLimitsConfig,
  normalizeAndValidateRiskLimitsInput,
  RiskLimitsValidationError,
  riskLimitsConfigEquals,
  toCapitalLimitsConfig,
  toOrgRiskLimitsMetadata,
  toTradeAbuseLimitsConfig,
  type NormalizedRiskLimitsConfig,
  type OrgRiskLimitsMetadata,
  type RiskLimitsRepository,
  type RiskLimitsService,
  type UpsertOrgRiskLimitsInput,
} from "@/lib/trader/risk/limits";
export {
  createKillSwitchResolver,
  createKillSwitchService,
  createPostgresKillSwitchRepository,
  createPostgresKillSwitchService,
  createSqliteKillSwitchRepository,
  createSqliteKillSwitchService,
  createAutomaticTriggerDispatcher,
  createPostgresAutomaticTriggerDispatcher,
  createPostgresGovernedRecoveryService,
  createSqliteAutomaticTriggerDispatcher,
  createSqliteGovernedRecoveryService,
  buildRecoveryPreview,
  CANONICAL_AUTO_TRIGGER_REASONS,
  TRUSTED_AUTOMATIC_TRIGGER_ACTOR,
  deriveContextFromTriggerTarget,
  triggerSignalToSwitchPlan,
  DEFAULT_RECOVERY_COOLING_OFF_MS,
  effectiveCoolingOffMs,
  KILL_SWITCH_ALREADY_ACTIVE,
  isAlreadyActiveError,
  isCoolingOffNotElapsedError,
  assertAllowedTransition,
  failClosedEffectiveState,
  isEnforcingState,
  mergeEffectiveContributions,
  mostRestrictiveEnforcementMode,
  KillSwitchAuthorizationError,
  KillSwitchConcurrencyError,
  KillSwitchCoolingOffNotElapsedError,
  KillSwitchValidationError,
  KillSwitchNotFoundError,
  IllegalKillSwitchTransitionError,
  UnsupportedKillSwitchScopeError,
  toKillSwitchView,
  type AnomalySwitchType,
  type AutomaticTriggerDispatcher,
  type AutomaticTriggerDispatcherDeps,
  type AutomaticTriggerDispatcherFactoryDeps,
  type CanonicalAutoTriggerReason,
  type EffectiveKillSwitchState,
  type EffectiveContribution,
  type GovernedRecoveryService,
  type KillSwitchActor,
  type KillSwitchRepository,
  type KillSwitchRow,
  type KillSwitchScopeKey,
  type KillSwitchService,
  type KillSwitchServiceDeps,
  type KillSwitchTarget,
  type KillSwitchTransitionResult,
  type KillSwitchTriggerBase,
  type KillSwitchTriggerPlan,
  type KillSwitchTriggerPort,
  type KillSwitchTriggerSignal,
  type KillSwitchView,
  type RecoveryPreview,
  type RequestClearInput,
  type TriggerOutcome,
  type TripKillSwitchInput,
} from "@/lib/trader/risk/kill-switch";
