export const HTX_BALANCE_SYNC_ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  CREDENTIAL_NOT_FOUND: "CREDENTIAL_NOT_FOUND",
  INVALID_CREDENTIAL_ID: "INVALID_CREDENTIAL_ID",
  MASTER_KEY_NOT_READY: "MASTER_KEY_NOT_READY",
  DECRYPT_UNAVAILABLE: "DECRYPT_UNAVAILABLE",
  BALANCE_SYNC_VALIDATION_FAILED: "BALANCE_SYNC_VALIDATION_FAILED",
  BALANCE_FETCH_FAILED: "BALANCE_FETCH_FAILED",
  INVALID_QUERY: "INVALID_QUERY",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type HtxBalanceSyncErrorCode =
  (typeof HTX_BALANCE_SYNC_ERROR_CODES)[keyof typeof HTX_BALANCE_SYNC_ERROR_CODES];

export const DEFAULT_BALANCE_SNAPSHOTS_LIST_LIMIT = 50;
export const MAX_BALANCE_SNAPSHOTS_LIST_LIMIT = 200;
