export const HTX_TRADE_HISTORY_SYNC_ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  CREDENTIAL_NOT_FOUND: "CREDENTIAL_NOT_FOUND",
  INVALID_CREDENTIAL_ID: "INVALID_CREDENTIAL_ID",
  INVALID_SYMBOL: "INVALID_SYMBOL",
  INVALID_BODY: "INVALID_BODY",
  MASTER_KEY_NOT_READY: "MASTER_KEY_NOT_READY",
  DECRYPT_UNAVAILABLE: "DECRYPT_UNAVAILABLE",
  TRADE_HISTORY_SYNC_VALIDATION_FAILED: "TRADE_HISTORY_SYNC_VALIDATION_FAILED",
  TRADE_HISTORY_FETCH_FAILED: "TRADE_HISTORY_FETCH_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type HtxTradeHistorySyncErrorCode =
  (typeof HTX_TRADE_HISTORY_SYNC_ERROR_CODES)[keyof typeof HTX_TRADE_HISTORY_SYNC_ERROR_CODES];

export const DEFAULT_TRADE_HISTORY_SNAPSHOTS_LIST_LIMIT = 50;
export const MAX_TRADE_HISTORY_SNAPSHOTS_LIST_LIMIT = 200;

/** POST sync-trades request body (DEE-350). */
export type TradeHistorySyncRequestBody = {
  symbol: string;
  limit?: number;
};
