export * from "@/lib/trader/types";
export * from "@/lib/trader/connectors";
export { writeTraderAuditLogSqlite, writeTraderAuditLogPostgres } from "@/lib/trader/audit/write";
export {
  getTraderOrgProfileSqlite,
  getTraderOrgProfilePostgres,
  insertTraderOrgProfileSqlite,
  insertTraderOrgProfilePostgres,
  getTraderOrgProfileByIdSqlite,
  type TraderOrgProfileRow,
} from "@/lib/trader/persistence/org-profile";
export { ensureTraderOrgProfileSqlite } from "@/lib/trader/provisioning/sqlite";
export { ensureTraderOrgProfilePostgres } from "@/lib/trader/provisioning/postgres";
export {
  createCredentialService,
  createPostgresCredentialService,
  createSqliteCredentialService,
  getCredentialRowByIdPostgres,
  getCredentialRowByIdSqlite,
  insertCredentialRowPostgres,
  insertCredentialRowSqlite,
  listCredentialRowsForOrgPostgres,
  listCredentialRowsForOrgSqlite,
  maskApiKey,
  revokeCredentialRowPostgres,
  revokeCredentialRowSqlite,
  type CredentialMetadata,
  type CredentialService,
  type ExchangeCredentialRow,
  type ExchangeCredentialStatus,
  type InsertExchangeCredentialRowInput,
} from "@/lib/trader/credentials";
export {
  absDecimal,
  approveDecision,
  buildRiskSnapshot,
  capitalReasonCodes,
  closeOnlyDecision,
  compareDecimal,
  createInMemoryOrderRateStore,
  createPostgresRiskEngineService,
  createPostgresRiskLimitsService,
  createPostgresKillSwitchService,
  createPostgresAutomaticTriggerDispatcher,
  createPostgresGovernedRecoveryService,
  createSqliteAutomaticTriggerDispatcher,
  createSqliteGovernedRecoveryService,
  buildRecoveryPreview,
  DEFAULT_RECOVERY_COOLING_OFF_MS,
  createRiskEngineService,
  createSqliteRiskEngineService,
  createSqliteRiskLimitsService,
  createSqliteKillSwitchService,
  DEFAULT_ORG_RISK_LIMITS,
  DECIMAL_SCALE,
  engineReasonCodes,
  evaluateCapitalLimits,
  evaluateTradeAbuse,
  buildKillSwitchAuditMetadata,
  CANONICAL_AUTO_TRIGGER_REASONS,
  mapEffectiveStateToDecision,
  triggerSignalToSwitchPlan,
  type AutomaticTriggerDispatcher,
  type GovernedRecoveryService,
  type KillSwitchTriggerPort,
  type KillSwitchTriggerSignal,
  type RecoveryPreview,
  type TriggerOutcome,
  killSwitchReasonCodes,
  InvalidDecimalError,
  isTerminalReject,
  mergeReasonCodes,
  multiplyDecimal,
  normalizeAndValidateRiskLimitsInput,
  parseDecimal,
  rejectDecision,
  resizeDecision,
  riskReasonCodes,
  RiskLimitsValidationError,
  stopAccountDecision,
  toCapitalLimitsConfig,
  toTradeAbuseLimitsConfig,
  type AccountRiskState,
  type CapitalLimitsConfig,
  type CapitalLimitsEvaluationInput,
  type EvaluateOrderRequestInput,
  type EffectiveKillSwitchState,
  type KillSwitchResolverPort,
  type KillSwitchReasonCode,
  type KillSwitchScopeKey,
  type KillSwitchService,
  type KillSwitchView,
  type NormalizedRiskLimitsConfig,
  type OrderRateStore,
  type OrgRiskLimitsMetadata,
  type RiskDecision,
  type RiskDecisionOutcome,
  type RiskEngineDecision,
  type RiskEngineService,
  type RiskEngineServiceDeps,
  type RiskLimitsService,
  type RiskReasonCode,
  type RiskSnapshot,
  type TradeAbuseEvaluationInput,
  type TradeAbuseLimitsConfig,
  type UpsertOrgRiskLimitsInput,
} from "@/lib/trader/risk";
export {
  createBalanceSnapshotService,
  createPostgresBalanceSnapshotService,
  createSqliteBalanceSnapshotService,
  handleBalanceSnapshotsGet,
  handleBalanceSyncPost,
  HTX_BALANCE_SYNC_ERROR_CODES,
  toBalanceSnapshotDto,
  type BalanceSnapshotDto,
  type BalanceSnapshotMetadata,
  type BalanceSnapshotService,
} from "@/lib/trader/balances";
export {
  assertTransition,
  isLegalTransition,
  isTerminal,
  mapConnectorStatusToOrderState,
  ORDER_TRANSITIONS,
  TERMINAL_ORDER_STATES,
  IllegalOrderTransitionError,
  orderEventTypeEnum,
  orderExecutionModeEnum,
  orderStateEnum,
  DuplicateOrderError,
  FillConflictError,
  OrderNotFoundError,
  OrderVersionConflictError,
  fillPayloadMatches,
  orderPayloadMatches,
  createPostgresOrderRepository,
  createPostgresOrderRepositoryFromExecutor,
  createSqliteOrderRepository,
  createOrderExecutionServiceFromDeps,
  createPostgresOrderExecutionService,
  createPostgresOrderExecutionServiceFromExecutor,
  createSqliteOrderExecutionService,
  canDispatch,
  createDefaultConnectorForMode,
  classifyReconciliation,
  classifyReconciliationForOrder,
  deriveTerminalDriftEscalationKind,
  createReconciliationServiceFromDeps,
  createPostgresReconciliationService,
  createPostgresReconciliationServiceFromExecutor,
  createSqliteReconciliationService,
  createPostgresStartupReconciliationRunner,
  createPostgresStartupReconciliationRunnerFromExecutor,
  createSqliteStartupReconciliationRunner,
  createStartupReconciliationRunnerFromDeps,
  runStartupReconciliation,
  POST_DISPATCH_RECONCILABLE_STATES,
  emptyReconciliationCounts,
  isPostDispatchReconcilable,
  isPreDispatchState,
  reconciliationClassificationEnum,
  mapOutcomeToTriggerSignals,
  dedupeTriggerSignals,
  processReconciliationEscalation,
  LiveExecutionNotSupportedError,
  UnsupportedExecutionModeError,
  type OrderExecutionService,
  type OrderExecutionServiceDeps,
  type SubmissionAuditIds,
  type SubmitOrderInput,
  type SubmitOrderResult,
  type ConnectorView,
  type EscalationActivationOutcome,
  type OrderReconciliationOutcome,
  type ReconciliationClassification,
  type ReconciliationEscalationKind,
  type ReconciliationEscalationReport,
  type ReconciliationReport,
  type ReconciliationService,
  type ReconciliationServiceDeps,
  type ReconcileTarget,
  type StartupReconciliationDeps,
  type StartupReconciliationResult,
  type StartupReconciliationRunner,
  type StartupExecutionMode,
  type CreateOrderInput,
  type FillRow,
  type OpenOrdersFilter,
  type OrderEventRow,
  type OrderRepository,
  type OrderRow,
  type RecordFillInput,
  type TransitionOrderInput,
  type OrderEventType,
  type OrderExecutionMode,
  type OrderSide,
  type OrderState,
  type OrderType,
} from "@/lib/trader/execution";
