-- DEE-383 / M8: RLS deny authenticated/anon on discovery tables

ALTER TABLE public.trader_discovery_research_campaign ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS trader_discovery_research_campaign_deny_authenticated_select ON public.trader_discovery_research_campaign;
CREATE POLICY trader_discovery_research_campaign_deny_authenticated_select ON public.trader_discovery_research_campaign FOR SELECT TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_research_campaign_deny_authenticated_insert ON public.trader_discovery_research_campaign;
CREATE POLICY trader_discovery_research_campaign_deny_authenticated_insert ON public.trader_discovery_research_campaign FOR INSERT TO authenticated, anon WITH CHECK (false);
DROP POLICY IF EXISTS trader_discovery_research_campaign_deny_authenticated_update ON public.trader_discovery_research_campaign;
CREATE POLICY trader_discovery_research_campaign_deny_authenticated_update ON public.trader_discovery_research_campaign FOR UPDATE TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_research_campaign_deny_authenticated_delete ON public.trader_discovery_research_campaign;
CREATE POLICY trader_discovery_research_campaign_deny_authenticated_delete ON public.trader_discovery_research_campaign FOR DELETE TO authenticated, anon USING (false);

ALTER TABLE public.trader_discovery_campaign_state_record ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS trader_discovery_campaign_state_record_deny_authenticated_select ON public.trader_discovery_campaign_state_record;
CREATE POLICY trader_discovery_campaign_state_record_deny_authenticated_select ON public.trader_discovery_campaign_state_record FOR SELECT TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_campaign_state_record_deny_authenticated_insert ON public.trader_discovery_campaign_state_record;
CREATE POLICY trader_discovery_campaign_state_record_deny_authenticated_insert ON public.trader_discovery_campaign_state_record FOR INSERT TO authenticated, anon WITH CHECK (false);
DROP POLICY IF EXISTS trader_discovery_campaign_state_record_deny_authenticated_update ON public.trader_discovery_campaign_state_record;
CREATE POLICY trader_discovery_campaign_state_record_deny_authenticated_update ON public.trader_discovery_campaign_state_record FOR UPDATE TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_campaign_state_record_deny_authenticated_delete ON public.trader_discovery_campaign_state_record;
CREATE POLICY trader_discovery_campaign_state_record_deny_authenticated_delete ON public.trader_discovery_campaign_state_record FOR DELETE TO authenticated, anon USING (false);

ALTER TABLE public.trader_discovery_research_question ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS trader_discovery_research_question_deny_authenticated_select ON public.trader_discovery_research_question;
CREATE POLICY trader_discovery_research_question_deny_authenticated_select ON public.trader_discovery_research_question FOR SELECT TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_research_question_deny_authenticated_insert ON public.trader_discovery_research_question;
CREATE POLICY trader_discovery_research_question_deny_authenticated_insert ON public.trader_discovery_research_question FOR INSERT TO authenticated, anon WITH CHECK (false);
DROP POLICY IF EXISTS trader_discovery_research_question_deny_authenticated_update ON public.trader_discovery_research_question;
CREATE POLICY trader_discovery_research_question_deny_authenticated_update ON public.trader_discovery_research_question FOR UPDATE TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_research_question_deny_authenticated_delete ON public.trader_discovery_research_question;
CREATE POLICY trader_discovery_research_question_deny_authenticated_delete ON public.trader_discovery_research_question FOR DELETE TO authenticated, anon USING (false);

ALTER TABLE public.trader_discovery_observation ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS trader_discovery_observation_deny_authenticated_select ON public.trader_discovery_observation;
CREATE POLICY trader_discovery_observation_deny_authenticated_select ON public.trader_discovery_observation FOR SELECT TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_observation_deny_authenticated_insert ON public.trader_discovery_observation;
CREATE POLICY trader_discovery_observation_deny_authenticated_insert ON public.trader_discovery_observation FOR INSERT TO authenticated, anon WITH CHECK (false);
DROP POLICY IF EXISTS trader_discovery_observation_deny_authenticated_update ON public.trader_discovery_observation;
CREATE POLICY trader_discovery_observation_deny_authenticated_update ON public.trader_discovery_observation FOR UPDATE TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_observation_deny_authenticated_delete ON public.trader_discovery_observation;
CREATE POLICY trader_discovery_observation_deny_authenticated_delete ON public.trader_discovery_observation FOR DELETE TO authenticated, anon USING (false);

ALTER TABLE public.trader_discovery_structure_cluster ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS trader_discovery_structure_cluster_deny_authenticated_select ON public.trader_discovery_structure_cluster;
CREATE POLICY trader_discovery_structure_cluster_deny_authenticated_select ON public.trader_discovery_structure_cluster FOR SELECT TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_structure_cluster_deny_authenticated_insert ON public.trader_discovery_structure_cluster;
CREATE POLICY trader_discovery_structure_cluster_deny_authenticated_insert ON public.trader_discovery_structure_cluster FOR INSERT TO authenticated, anon WITH CHECK (false);
DROP POLICY IF EXISTS trader_discovery_structure_cluster_deny_authenticated_update ON public.trader_discovery_structure_cluster;
CREATE POLICY trader_discovery_structure_cluster_deny_authenticated_update ON public.trader_discovery_structure_cluster FOR UPDATE TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_structure_cluster_deny_authenticated_delete ON public.trader_discovery_structure_cluster;
CREATE POLICY trader_discovery_structure_cluster_deny_authenticated_delete ON public.trader_discovery_structure_cluster FOR DELETE TO authenticated, anon USING (false);

ALTER TABLE public.trader_discovery_hypothesis_proposal ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS trader_discovery_hypothesis_proposal_deny_authenticated_select ON public.trader_discovery_hypothesis_proposal;
CREATE POLICY trader_discovery_hypothesis_proposal_deny_authenticated_select ON public.trader_discovery_hypothesis_proposal FOR SELECT TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_hypothesis_proposal_deny_authenticated_insert ON public.trader_discovery_hypothesis_proposal;
CREATE POLICY trader_discovery_hypothesis_proposal_deny_authenticated_insert ON public.trader_discovery_hypothesis_proposal FOR INSERT TO authenticated, anon WITH CHECK (false);
DROP POLICY IF EXISTS trader_discovery_hypothesis_proposal_deny_authenticated_update ON public.trader_discovery_hypothesis_proposal;
CREATE POLICY trader_discovery_hypothesis_proposal_deny_authenticated_update ON public.trader_discovery_hypothesis_proposal FOR UPDATE TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_hypothesis_proposal_deny_authenticated_delete ON public.trader_discovery_hypothesis_proposal;
CREATE POLICY trader_discovery_hypothesis_proposal_deny_authenticated_delete ON public.trader_discovery_hypothesis_proposal FOR DELETE TO authenticated, anon USING (false);

ALTER TABLE public.trader_discovery_consolidation_record ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS trader_discovery_consolidation_record_deny_authenticated_select ON public.trader_discovery_consolidation_record;
CREATE POLICY trader_discovery_consolidation_record_deny_authenticated_select ON public.trader_discovery_consolidation_record FOR SELECT TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_consolidation_record_deny_authenticated_insert ON public.trader_discovery_consolidation_record;
CREATE POLICY trader_discovery_consolidation_record_deny_authenticated_insert ON public.trader_discovery_consolidation_record FOR INSERT TO authenticated, anon WITH CHECK (false);
DROP POLICY IF EXISTS trader_discovery_consolidation_record_deny_authenticated_update ON public.trader_discovery_consolidation_record;
CREATE POLICY trader_discovery_consolidation_record_deny_authenticated_update ON public.trader_discovery_consolidation_record FOR UPDATE TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_consolidation_record_deny_authenticated_delete ON public.trader_discovery_consolidation_record;
CREATE POLICY trader_discovery_consolidation_record_deny_authenticated_delete ON public.trader_discovery_consolidation_record FOR DELETE TO authenticated, anon USING (false);

ALTER TABLE public.trader_discovery_strategy_synthesis ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS trader_discovery_strategy_synthesis_deny_authenticated_select ON public.trader_discovery_strategy_synthesis;
CREATE POLICY trader_discovery_strategy_synthesis_deny_authenticated_select ON public.trader_discovery_strategy_synthesis FOR SELECT TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_strategy_synthesis_deny_authenticated_insert ON public.trader_discovery_strategy_synthesis;
CREATE POLICY trader_discovery_strategy_synthesis_deny_authenticated_insert ON public.trader_discovery_strategy_synthesis FOR INSERT TO authenticated, anon WITH CHECK (false);
DROP POLICY IF EXISTS trader_discovery_strategy_synthesis_deny_authenticated_update ON public.trader_discovery_strategy_synthesis;
CREATE POLICY trader_discovery_strategy_synthesis_deny_authenticated_update ON public.trader_discovery_strategy_synthesis FOR UPDATE TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_strategy_synthesis_deny_authenticated_delete ON public.trader_discovery_strategy_synthesis;
CREATE POLICY trader_discovery_strategy_synthesis_deny_authenticated_delete ON public.trader_discovery_strategy_synthesis FOR DELETE TO authenticated, anon USING (false);

ALTER TABLE public.trader_discovery_evidence_record ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS trader_discovery_evidence_record_deny_authenticated_select ON public.trader_discovery_evidence_record;
CREATE POLICY trader_discovery_evidence_record_deny_authenticated_select ON public.trader_discovery_evidence_record FOR SELECT TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_evidence_record_deny_authenticated_insert ON public.trader_discovery_evidence_record;
CREATE POLICY trader_discovery_evidence_record_deny_authenticated_insert ON public.trader_discovery_evidence_record FOR INSERT TO authenticated, anon WITH CHECK (false);
DROP POLICY IF EXISTS trader_discovery_evidence_record_deny_authenticated_update ON public.trader_discovery_evidence_record;
CREATE POLICY trader_discovery_evidence_record_deny_authenticated_update ON public.trader_discovery_evidence_record FOR UPDATE TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_evidence_record_deny_authenticated_delete ON public.trader_discovery_evidence_record;
CREATE POLICY trader_discovery_evidence_record_deny_authenticated_delete ON public.trader_discovery_evidence_record FOR DELETE TO authenticated, anon USING (false);

ALTER TABLE public.trader_discovery_comparison_score ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS trader_discovery_comparison_score_deny_authenticated_select ON public.trader_discovery_comparison_score;
CREATE POLICY trader_discovery_comparison_score_deny_authenticated_select ON public.trader_discovery_comparison_score FOR SELECT TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_comparison_score_deny_authenticated_insert ON public.trader_discovery_comparison_score;
CREATE POLICY trader_discovery_comparison_score_deny_authenticated_insert ON public.trader_discovery_comparison_score FOR INSERT TO authenticated, anon WITH CHECK (false);
DROP POLICY IF EXISTS trader_discovery_comparison_score_deny_authenticated_update ON public.trader_discovery_comparison_score;
CREATE POLICY trader_discovery_comparison_score_deny_authenticated_update ON public.trader_discovery_comparison_score FOR UPDATE TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_comparison_score_deny_authenticated_delete ON public.trader_discovery_comparison_score;
CREATE POLICY trader_discovery_comparison_score_deny_authenticated_delete ON public.trader_discovery_comparison_score FOR DELETE TO authenticated, anon USING (false);

ALTER TABLE public.trader_discovery_promotion_proposal ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS trader_discovery_promotion_proposal_deny_authenticated_select ON public.trader_discovery_promotion_proposal;
CREATE POLICY trader_discovery_promotion_proposal_deny_authenticated_select ON public.trader_discovery_promotion_proposal FOR SELECT TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_promotion_proposal_deny_authenticated_insert ON public.trader_discovery_promotion_proposal;
CREATE POLICY trader_discovery_promotion_proposal_deny_authenticated_insert ON public.trader_discovery_promotion_proposal FOR INSERT TO authenticated, anon WITH CHECK (false);
DROP POLICY IF EXISTS trader_discovery_promotion_proposal_deny_authenticated_update ON public.trader_discovery_promotion_proposal;
CREATE POLICY trader_discovery_promotion_proposal_deny_authenticated_update ON public.trader_discovery_promotion_proposal FOR UPDATE TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_promotion_proposal_deny_authenticated_delete ON public.trader_discovery_promotion_proposal;
CREATE POLICY trader_discovery_promotion_proposal_deny_authenticated_delete ON public.trader_discovery_promotion_proposal FOR DELETE TO authenticated, anon USING (false);

ALTER TABLE public.trader_discovery_retirement_record ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS trader_discovery_retirement_record_deny_authenticated_select ON public.trader_discovery_retirement_record;
CREATE POLICY trader_discovery_retirement_record_deny_authenticated_select ON public.trader_discovery_retirement_record FOR SELECT TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_retirement_record_deny_authenticated_insert ON public.trader_discovery_retirement_record;
CREATE POLICY trader_discovery_retirement_record_deny_authenticated_insert ON public.trader_discovery_retirement_record FOR INSERT TO authenticated, anon WITH CHECK (false);
DROP POLICY IF EXISTS trader_discovery_retirement_record_deny_authenticated_update ON public.trader_discovery_retirement_record;
CREATE POLICY trader_discovery_retirement_record_deny_authenticated_update ON public.trader_discovery_retirement_record FOR UPDATE TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_discovery_retirement_record_deny_authenticated_delete ON public.trader_discovery_retirement_record;
CREATE POLICY trader_discovery_retirement_record_deny_authenticated_delete ON public.trader_discovery_retirement_record FOR DELETE TO authenticated, anon USING (false);
