-- DEE-415 / HTR-WP21: calibration + abstention outcome records RLS (ADR-0007)

ALTER TABLE public.trader_calibration_observation_record ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS trader_calibration_observation_record_deny_authenticated_select ON public.trader_calibration_observation_record;
CREATE POLICY trader_calibration_observation_record_deny_authenticated_select ON public.trader_calibration_observation_record FOR SELECT TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_calibration_observation_record_deny_authenticated_insert ON public.trader_calibration_observation_record;
CREATE POLICY trader_calibration_observation_record_deny_authenticated_insert ON public.trader_calibration_observation_record FOR INSERT TO authenticated, anon WITH CHECK (false);
DROP POLICY IF EXISTS trader_calibration_observation_record_deny_authenticated_update ON public.trader_calibration_observation_record;
CREATE POLICY trader_calibration_observation_record_deny_authenticated_update ON public.trader_calibration_observation_record FOR UPDATE TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_calibration_observation_record_deny_authenticated_delete ON public.trader_calibration_observation_record;
CREATE POLICY trader_calibration_observation_record_deny_authenticated_delete ON public.trader_calibration_observation_record FOR DELETE TO authenticated, anon USING (false);
--> statement-breakpoint
ALTER TABLE public.trader_calibration_snapshot_record ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS trader_calibration_snapshot_record_deny_authenticated_select ON public.trader_calibration_snapshot_record;
CREATE POLICY trader_calibration_snapshot_record_deny_authenticated_select ON public.trader_calibration_snapshot_record FOR SELECT TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_calibration_snapshot_record_deny_authenticated_insert ON public.trader_calibration_snapshot_record;
CREATE POLICY trader_calibration_snapshot_record_deny_authenticated_insert ON public.trader_calibration_snapshot_record FOR INSERT TO authenticated, anon WITH CHECK (false);
DROP POLICY IF EXISTS trader_calibration_snapshot_record_deny_authenticated_update ON public.trader_calibration_snapshot_record;
CREATE POLICY trader_calibration_snapshot_record_deny_authenticated_update ON public.trader_calibration_snapshot_record FOR UPDATE TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_calibration_snapshot_record_deny_authenticated_delete ON public.trader_calibration_snapshot_record;
CREATE POLICY trader_calibration_snapshot_record_deny_authenticated_delete ON public.trader_calibration_snapshot_record FOR DELETE TO authenticated, anon USING (false);
--> statement-breakpoint
ALTER TABLE public.trader_abstention_outcome_record ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS trader_abstention_outcome_record_deny_authenticated_select ON public.trader_abstention_outcome_record;
CREATE POLICY trader_abstention_outcome_record_deny_authenticated_select ON public.trader_abstention_outcome_record FOR SELECT TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_abstention_outcome_record_deny_authenticated_insert ON public.trader_abstention_outcome_record;
CREATE POLICY trader_abstention_outcome_record_deny_authenticated_insert ON public.trader_abstention_outcome_record FOR INSERT TO authenticated, anon WITH CHECK (false);
DROP POLICY IF EXISTS trader_abstention_outcome_record_deny_authenticated_update ON public.trader_abstention_outcome_record;
CREATE POLICY trader_abstention_outcome_record_deny_authenticated_update ON public.trader_abstention_outcome_record FOR UPDATE TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_abstention_outcome_record_deny_authenticated_delete ON public.trader_abstention_outcome_record;
CREATE POLICY trader_abstention_outcome_record_deny_authenticated_delete ON public.trader_abstention_outcome_record FOR DELETE TO authenticated, anon USING (false);
