-- DEE-534 / WP-KNOWLEDGE-STATE: knowledge checkpoint v2 RLS (ADR-0007)

ALTER TABLE public.trader_knowledge_state_checkpoint_v2 ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS trader_knowledge_state_checkpoint_v2_deny_authenticated_select ON public.trader_knowledge_state_checkpoint_v2;
CREATE POLICY trader_knowledge_state_checkpoint_v2_deny_authenticated_select ON public.trader_knowledge_state_checkpoint_v2 FOR SELECT TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_knowledge_state_checkpoint_v2_deny_authenticated_insert ON public.trader_knowledge_state_checkpoint_v2;
CREATE POLICY trader_knowledge_state_checkpoint_v2_deny_authenticated_insert ON public.trader_knowledge_state_checkpoint_v2 FOR INSERT TO authenticated, anon WITH CHECK (false);
DROP POLICY IF EXISTS trader_knowledge_state_checkpoint_v2_deny_authenticated_update ON public.trader_knowledge_state_checkpoint_v2;
CREATE POLICY trader_knowledge_state_checkpoint_v2_deny_authenticated_update ON public.trader_knowledge_state_checkpoint_v2 FOR UPDATE TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_knowledge_state_checkpoint_v2_deny_authenticated_delete ON public.trader_knowledge_state_checkpoint_v2;
CREATE POLICY trader_knowledge_state_checkpoint_v2_deny_authenticated_delete ON public.trader_knowledge_state_checkpoint_v2 FOR DELETE TO authenticated, anon USING (false);
