-- DEE-532 / WP-EXECOPP-QUAL: scientific admission receipt RLS (ADR-0007)

ALTER TABLE public.trader_scientific_admission_receipt_v1 ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS trader_scientific_admission_receipt_v1_deny_authenticated_select ON public.trader_scientific_admission_receipt_v1;
CREATE POLICY trader_scientific_admission_receipt_v1_deny_authenticated_select ON public.trader_scientific_admission_receipt_v1 FOR SELECT TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_scientific_admission_receipt_v1_deny_authenticated_insert ON public.trader_scientific_admission_receipt_v1;
CREATE POLICY trader_scientific_admission_receipt_v1_deny_authenticated_insert ON public.trader_scientific_admission_receipt_v1 FOR INSERT TO authenticated, anon WITH CHECK (false);
DROP POLICY IF EXISTS trader_scientific_admission_receipt_v1_deny_authenticated_update ON public.trader_scientific_admission_receipt_v1;
CREATE POLICY trader_scientific_admission_receipt_v1_deny_authenticated_update ON public.trader_scientific_admission_receipt_v1 FOR UPDATE TO authenticated, anon USING (false);
DROP POLICY IF EXISTS trader_scientific_admission_receipt_v1_deny_authenticated_delete ON public.trader_scientific_admission_receipt_v1;
CREATE POLICY trader_scientific_admission_receipt_v1_deny_authenticated_delete ON public.trader_scientific_admission_receipt_v1 FOR DELETE TO authenticated, anon USING (false);
