export const HTX_POSITION_SYNC_ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  CREDENTIAL_NOT_FOUND: "CREDENTIAL_NOT_FOUND",
  INVALID_CREDENTIAL_ID: "INVALID_CREDENTIAL_ID",
  MASTER_KEY_NOT_READY: "MASTER_KEY_NOT_READY",
  DECRYPT_UNAVAILABLE: "DECRYPT_UNAVAILABLE",
  POSITION_SYNC_VALIDATION_FAILED: "POSITION_SYNC_VALIDATION_FAILED",
  POSITION_FETCH_FAILED: "POSITION_FETCH_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type HtxPositionSyncErrorCode =
  (typeof HTX_POSITION_SYNC_ERROR_CODES)[keyof typeof HTX_POSITION_SYNC_ERROR_CODES];

export const DEFAULT_POSITION_SNAPSHOTS_LIST_LIMIT = 50;
export const MAX_POSITION_SNAPSHOTS_LIST_LIMIT = 200;
