/** Generated by generate-research-understanding-manifest.ts; maintained source identity, not binary attestation. */
export const COMPUTATION_SOURCE_MANIFEST = [
  {
    "path": "lib/trader/exits/atr-estimator.ts",
    "sha256": "b9626cb4e25001331ecc026267cdffa1ef889c16ea15fc586edc213019565534"
  },
  {
    "path": "lib/trader/intelligence/feature-engine-v0.ts",
    "sha256": "e0f2fb6aba48c073ce9a42402cd1141433ee81898cbb83f369b1224921c27ca0"
  },
  {
    "path": "lib/trader/intelligence/htr-semantic-canonical-json.ts",
    "sha256": "b50dc925e7d3b10bd9436100f20ec7fee31f7d278b8b9ff549efd7894e0dce5d"
  },
  {
    "path": "lib/trader/intelligence/information-sufficiency/index.ts",
    "sha256": "cdb12adaa8e4961365ff420474384af960e3c418dfdfa7af309e8238223747fb"
  },
  {
    "path": "lib/trader/intelligence/information-sufficiency/information-sufficiency-runtime-authority-v2.ts",
    "sha256": "1fada099118bd8b5d727e684d40b1c70bbbcc4997f93bf759bfa19483bba8f32"
  },
  {
    "path": "lib/trader/intelligence/information-sufficiency/information-sufficiency-v2.ts",
    "sha256": "12e6802557f0567095314947db1b36b604eed853a1ff9a7b17ee614ee738684a"
  },
  {
    "path": "lib/trader/intelligence/market-understanding-bridge-v0.ts",
    "sha256": "7c3dcf97f932a37cc1b673a2fed86f3550690e41ebf74d404a0a431d2a00f9c9"
  },
  {
    "path": "lib/trader/intelligence/market-understanding-evidence-attribution-v1.ts",
    "sha256": "398fe450cfd7e66a245578790209c2f0546be4e937681a3526c6e0d66e77590a"
  },
  {
    "path": "lib/trader/intelligence/market-understanding.types.ts",
    "sha256": "fc3d969e1eb279e45325bd110926bdf2d39a5f37c509a654a046d715f930b33f"
  },
  {
    "path": "lib/trader/intelligence/reconstruction/bar-utils.ts",
    "sha256": "3ff8c9a0b092845de425425bc8d3309178a584d7aab8e97de64ba0e911b6483c"
  },
  {
    "path": "lib/trader/intelligence/reconstruction/build-reconstruction-snapshot.ts",
    "sha256": "adf3eea0ec67f21bdd91d75c3500583fe5c3d7185e2522aa87d9dffac20cbad6"
  },
  {
    "path": "lib/trader/intelligence/reconstruction/reconstruction-assembly.ts",
    "sha256": "e8f2c28982b424cf8bc7e7940dc5999b0cb5045d2d13d241195eb038d361ffeb"
  },
  {
    "path": "lib/trader/intelligence/reconstruction/reconstruction-kernel.ts",
    "sha256": "517d5141a4f93825f616dd8ab4af12396bb6ca7b36fd3173d7eb13db468efeaa"
  },
  {
    "path": "lib/trader/intelligence/reconstruction/reconstruction.types.ts",
    "sha256": "30910d8a79f193de6841c12d5c6da1338ac38503a46bf1a931d1042479978c09"
  },
  {
    "path": "lib/trader/intelligence/strategies/registry-metadata.ts",
    "sha256": "61e1e99f690548f5d60c96c96b6ff0aad4a9b1744d25f4c0e97346083dc511c3"
  },
  {
    "path": "lib/trader/intelligence/types.ts",
    "sha256": "ed5bacef1e7135fce6636a14d4dee357c5b477fd34fd464496919920da93a99f"
  },
  {
    "path": "lib/trader/market-data/canvas/incremental-mtf.ts",
    "sha256": "fd600f988a1230561426022a8359f4d49b24e762c67d373c745ef87d5ec02748"
  },
  {
    "path": "lib/trader/market-data/fusion/context-fusion-v1.ts",
    "sha256": "b3bafa27d917aab6ca61290b0e10fbd6c0827a9a0b21225cf9cae3e035c0eb35"
  },
  {
    "path": "lib/trader/market-data/fusion/cross-venue-triangulation.ts",
    "sha256": "068542bb18aea95b35ecc94ef352b396b323fd9ef2bf3de1c8ec36f4fbf0f865"
  },
  {
    "path": "lib/trader/market-data/mtf/bar-interval-duration.ts",
    "sha256": "e44500a58d050f71307336992e61a69a994a4eb47bd7d43e20e32c03667c652a"
  },
  {
    "path": "lib/trader/market-data/mtf/mtf-backdrop-classifier.ts",
    "sha256": "aa2bdb37b8eb785b436cfc7891121d46688e43cfc69cbadbd9202c4478c2a2e8"
  },
  {
    "path": "lib/trader/market-data/mtf/mtf-bucket-accumulator.ts",
    "sha256": "93b44e850e9555e95308d9c54b76021c69ff15a5c292857f8cc05661e0aba8c7"
  },
  {
    "path": "lib/trader/market-data/mtf/replay-mtf-resampler.ts",
    "sha256": "317c7370eaf36fabb506e80b4fc2a2741cec8e3cbad337be741ab196c0d15696"
  },
  {
    "path": "lib/trader/market-data/normalization/canonical-pit-contract.ts",
    "sha256": "cdbbbbaa9e441bf12768179e1a34faf766a2c89a7fec49829b255b6709c4d7e8"
  },
  {
    "path": "lib/trader/market-data/normalization/gateway-to-canonical-pit.ts",
    "sha256": "263e3fe27385c2d9cbee851eb69b7416d66d6be7d18cedd023273f9a8e430362"
  },
  {
    "path": "lib/trader/market-data/normalization/normalize-observation.ts",
    "sha256": "e00b9fe938afb174c6992bbf5cb028681739af6cc53575258a56bf0d45dd140e"
  },
  {
    "path": "lib/trader/market-data/observation-types.ts",
    "sha256": "f3c9ac104a42fbb7ba8388b8da5f23e4dd7e81f5c8e7f95873b863bf839f2434"
  },
  {
    "path": "lib/trader/market-data/provider-registry.ts",
    "sha256": "e7122c6573b3f8f2f4513b663b681c8b62438898c8cf0c597e7ba7ed97f0d0e2"
  },
  {
    "path": "lib/trader/market-data/reliability/freshness-policy.ts",
    "sha256": "1d94348c61bc600d08d83736823f4ee1005ac3ef3ef9d389d0112b2c186daa2b"
  },
  {
    "path": "lib/trader/market-data/reliability/provider-health.ts",
    "sha256": "7594ead3bd195686c5eb498913e74b15781eec6d3045c7a6dc5c0f4b4a729759"
  },
  {
    "path": "lib/trader/market-data/replay-bar-limits.ts",
    "sha256": "8c020b26a2df2e523f6f03fcd04f9c10929d946ef0190c91a13e3c86bb3560bf"
  },
  {
    "path": "lib/trader/market-data/session/asian-range-corridor.ts",
    "sha256": "7a8164b0f430489180648d161ae675ae550b682206d73ceb04858d482c1f9039"
  },
  {
    "path": "lib/trader/market-data/session/session-phase-classifier.ts",
    "sha256": "907735072ff1d71ecb15a2260ab225674d0c11a10771cd2c2e7dfc0e8ef9e45f"
  },
  {
    "path": "lib/trader/market-data/validation/validate-observation.ts",
    "sha256": "e6318a25c05b9678f35d400e231d5d36970d1674ccb93b2c60b1dfea590b04a4"
  },
  {
    "path": "lib/trader/mi/canonical-observation-v1.ts",
    "sha256": "325014f522d11684d9d69632a21c4b08d593b4c281fb754e61cf5bcb74aeceb1"
  },
  {
    "path": "lib/trader/mi/serialize-source-trust.ts",
    "sha256": "056cea2d4725e6b8305525ee000aa452ca6ba911ae1af5e574f7314b1d20f867"
  },
  {
    "path": "lib/trader/mi/source-trust.types.ts",
    "sha256": "e30b08fc150a2a0c4236aa1aeb1261eb58302282d09dfe311891f06343d35f44"
  },
  {
    "path": "lib/trader/paper/durable-noncapital/normalize-mandatory-packet-v1.ts",
    "sha256": "076b918e686dca8a456409dc59bd237e8124aa9f32765bcfa715c84e5ca425ad"
  },
  {
    "path": "lib/trader/paper/durable-noncapital/recorded-analysis-v1.ts",
    "sha256": "05bb4444cd3b4ea72d494026260df165c9cc8f419a1261bfaad8114c2dea7cbb"
  },
  {
    "path": "lib/trader/paper/durable-noncapital/recorded-source-read-validation-v1.ts",
    "sha256": "40f13cef7e2320bea2f25b6615e7eca37ec8626099fbd65b493d5b6a477a29ef"
  },
  {
    "path": "lib/trader/paper/paper-evaluation-export.types.ts",
    "sha256": "ea79a002174370a6f4088e90c7ca46167545e48bd0838d8ca08554fb563b6964"
  },
  {
    "path": "lib/trader/paper/research-understanding-v1/admission.ts",
    "sha256": "c97c3abb710ee655568c315eab72a879d6d5b4322626be1b61eb9b0a942ef5b6"
  },
  {
    "path": "lib/trader/paper/research-understanding-v1/contract.ts",
    "sha256": "0cfa04580b8396323fdf673d1100ac99cbe0e3ece3506cfa58a856410bb7cca9"
  },
  {
    "path": "lib/trader/paper/research-understanding-v1/evaluate.ts",
    "sha256": "a17fdaa7318fda49f6cc1cc31a388be957e4a6bf225e8b21c3437de16455b83f"
  },
  {
    "path": "lib/trader/paper/serialize-paper-evaluation-export.ts",
    "sha256": "bf74b28ef8152d098a391e6090646ffa6f29fb39529d0eea81c5e3aec5a41f31"
  },
  {
    "path": "lib/trader/research/digest.ts",
    "sha256": "5c69368f5681efa1bceabea2e0bbb4dd77f9ecb11757bbaa98653b7782ecdbb0"
  },
  {
    "path": "lib/trader/risk/numeric.ts",
    "sha256": "fe5ec7420106c8b078b7393fa171bdbba19d77ab12b65754f11eb7b2af41fc51"
  },
  {
    "path": "lib/trader/runtime-v2/recorded-noncapital-input-v2.ts",
    "sha256": "fa845f95d8598325c144754b4b908ea7d74fe2d41c299999367c4b059c46ae79"
  },
  {
    "path": "lib/trader/symbols/historical-instrument.ts",
    "sha256": "b76e0104bf35e0591b37e9bf8e75039b555b2f7e88874f6dea923382864d3e25"
  }
] as const;
export const COMPUTATION_SOURCE_MANIFEST_DIGEST = "abb0618c8dc0298376fe7513c184d6c20f67aa93551caadfb1febf4f3de9f3b4";
