import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { erfCody715V1, normalCdfCody715V1 } from "@/lib/trader/research/benchmark/cdf-erf-cody715-v1";
import { erfCody715V2, normalCdfCody715V2 } from "@/lib/trader/research/benchmark/cdf-erf-cody715-v2";
import { CDF_REFERENCE_AMENDMENT_DIGEST } from "@/lib/trader/research/benchmark/cdf-evidence-protocol-v2";
import { evaluateMandatoryBaselineV1, type BaselineContext } from "@/lib/trader/research/benchmark/baseline-models-v1";
import { assertTerminalProbabilityVectorV2 } from "@/lib/trader/research/benchmark/terminal-scoring-protocol-v2";

describe("DEE-993 Cody JINT=0 conformance", () => {
  it("reproduces the preserved v1 defect and fixes the large positive tail", () => {
    expect(normalCdfCody715V1(1e9)).toBeLessThan(normalCdfCody715V1(1e6));
    expect(normalCdfCody715V2(1e9)).toBe(1);
    expect(normalCdfCody715V2(-1e9)).toBe(0);
  });
  it.each([26.543, 26.543 + 1e-12, 6.71e7 - 1, 6.71e7, 6.71e7 + 1, 1e9, 2.53e307, Number.MAX_VALUE, Infinity])(
    "saturates both erf tails at %s as prescribed for JINT=0", x => {
      expect(erfCody715V2(x)).toBe(1);
      expect(erfCody715V2(-x)).toBe(-1);
    });
  it("preserves NaN, infinities and signed zero behavior", () => {
    expect(erfCody715V2(NaN)).toBeNaN();
    expect(normalCdfCody715V2(NaN)).toBeNaN();
    expect(normalCdfCody715V2(Infinity)).toBe(1);
    expect(normalCdfCody715V2(-Infinity)).toBe(0);
    expect(Object.is(erfCody715V2(-0), -0)).toBe(true);
  });
  it("leaves the ordinary-domain algorithm bit-identical to preserved v1", () => {
    for (const x of [-26.542999999, -8, -4.000001, -4, -0.46875001, -0.46875, -1e-17, 0,
      1e-17, 0.46875, 0.46875001, 1, 4, 4.000001, 8, 26.542999999]) {
      expect(erfCody715V2(x)).toBe(erfCody715V1(x));
    }
    // Standard normal known answers, not generated by either implementation.
    expect(normalCdfCody715V2(0)).toBe(0.5);
    expect(normalCdfCody715V2(1)).toBeCloseTo(0.8413447460685429, 15);
    expect(normalCdfCody715V2(-3)).toBeCloseTo(0.0013498980316300945, 15);
  });
  it("is monotone across every rational branch and former huge-argument boundary", () => {
    const points = [-Infinity, -1e308, -1e9, -6.71e7-1, -6.71e7, -6.71e7+1,
      -26.543001, -26.543, -26.542999, -4.000001, -4, -3.999999,
      -0.468751, -0.46875, -0.468749, 0, 0.468749, 0.46875, 0.468751,
      3.999999, 4, 4.000001, 26.542999, 26.543, 26.543001,
      6.71e7-1, 6.71e7, 6.71e7+1, 1e9, 1e308, Infinity];
    for (let i = 1; i < points.length; i++) {
      expect(erfCody715V2(points[i]!)).toBeGreaterThanOrEqual(erfCody715V2(points[i-1]!));
      expect(normalCdfCody715V2(points[i]!)).toBeGreaterThanOrEqual(normalCdfCody715V2(points[i-1]!));
    }
  });
  it.each(["gaussian-pop-std/v2", "ewma-lambda094/v3"] as const)(
    "keeps extreme %s bucket mass valid without normalization", id => {
      const context: BaselineContext = {
        developmentReturns: [-1,1],
        grid: { bucketCount: 7, edges: [-1e9,-1e6,-1,1,1e6,1e9] },
        history: Array(2000).fill(1),
        historyMinuteOpenTimesMs: Array.from({length:2000}, (_,i)=>i*60000),
        primaryHorizonMinutes:30,
      };
      const result = evaluateMandatoryBaselineV1(id, context);
      expect(result.status).toBe("AVAILABLE");
      if (result.status !== "AVAILABLE") throw new Error("unexpected unavailable");
      expect(() => assertTerminalProbabilityVectorV2(result.probabilities)).not.toThrow();
      expect(result.probabilities.reduce((a,b)=>a+b,0)).toBeCloseTo(1,15);
      expect(() => assertTerminalProbabilityVectorV2([0.1,0,0,0,0,0,0])).toThrow();
    });
  it("binds exact approved amendment bytes", () => {
    expect(createHash("sha256").update(readFileSync("docs/plans/dee-993-cody-amendment-v1.md")).digest("hex"))
      .toBe(CDF_REFERENCE_AMENDMENT_DIGEST);
  });
});
